# Generated by Django 6.0 on 2026-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('region_ar', models.CharField(blank=True, max_length=200)),
                ('region_en', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('distance_info_ar', models.CharField(blank=True, max_length=300)),
                ('distance_info_en', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='places/main/')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
