# Generated by Django 6.0 on 2026-02-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('caption_ar', models.CharField(blank=True, max_length=255, verbose_name='تعليق (عربي)')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='Caption (English)')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب الصورة')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'verbose_name': 'صورة المكان',
                'verbose_name_plural': 'صور المكان',
                'ordering': ['order'],
            },
        ),
    ]
