# Generated by Django 6.0 on 2026-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options_place_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
